### ISSUE TITLE
Fury does not work with quarkus-rest in native mode

### ISSUE THREAD

**Issue by zhfeng** [quarkiverse/quarkus-fury#32]
When we have a integration of fury with `quarkus-rest` to do (de)serialize by supporting `application/fury` media type. It have to add a `@RegisterForReflection` in the JAX-RS resource, otherwise it faill to find such method like the below one in the native mode.
```java 
    @POST
    @Path("/test")
    @Produces("application/fury")
    @Consumes("application/fury")
    public Bar testBar(Bar obj) {
        ...
   }
```

BTW, it works with `quarkus-resteasy`.

**Comment by zhfeng** [comment]
@gastaldi @geoand This is the reproducer https://github.com/zhfeng/fury_reactive_rest_reproducer

```
./mvwn clean verify -Dnative
```

It will fail with
```
2024-11-16 13:30:15,212 INFO  [io.quarkus] (main) code-with-quarkus-app 1.0.0-SNAPSHOT native (powered by Quarkus 3.16.3) started in 0.015s. Listening on: http://0.0.0.0:8081
2024-11-16 13:30:15,212 INFO  [io.quarkus] (main) Profile prod activated. 
2024-11-16 13:30:15,212 INFO  [io.quarkus] (main) Installed features: [cdi, fury, rest, rest-jackson, smallrye-context-propagation, vertx]
2024-11-16 01:30:15 INFO  Fury:160 [main] - Created new fury org.apache.fury.Fury@3d88ce0e
2024-11-16 13:30:16,042 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /test/fury failed, error id: 7e7ecd63-eef3-41a6-9e17-55b58feb1112-1: java.lang.RuntimeException: java.lang.NoSuchMethodException: org.acme.GreetingResource.testBar(org.acme.Bar)
	at org.jboss.resteasy.reactive.server.spi.ResteasyReactiveResourceInfo.getMethod(ResteasyReactiveResourceInfo.java:84)
	at org.jboss.resteasy.reactive.server.spi.ResteasyReactiveResourceInfo.getParameterAnnotations(ResteasyReactiveResourceInfo.java:125)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.getAnnotations(RequestDeserializeHandler.java:133)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.isReadable(RequestDeserializeHandler.java:118)
	at org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler.handle(RequestDeserializeHandler.java:78)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:135)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:627)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@21.0.5/java.lang.Thread.runWith(Thread.java:1596)
	at java.base@21.0.5/java.lang.Thread.run(Thread.java:1583)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
Caused by: java.lang.NoSuchMethodException: org.acme.GreetingResource.testBar(org.acme.Bar)
	at java.base@21.0.5/java.lang.Class.checkMethod(DynamicHub.java:1078)
	at java.base@21.0.5/java.lang.Class.getMethod(DynamicHub.java:1063)
	at org.jboss.resteasy.reactive.server.spi.ResteasyReactiveResourceInfo.getMethod(ResteasyReactiveResourceInfo.java:79)
	... 18 more

```

There are two test methods for testing `application/json`  and `application/fury`. It only fails when testing with `application/fury`.

**Comment by geoand** [comment]
Thanks, I'll check next week
