### ISSUE TITLE
Can not create record Serializer

### ISSUE THREAD

**Issue by zhfeng** [quarkiverse/quarkus-fury#49]
If there is a record in the project
```java
@FurySerialization
record Bar(int f1, String f2) {
}
```

The application is failing to startup

```
java.lang.RuntimeException: java.lang.ExceptionInInitializerError
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:628)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:712)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:289)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:241)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:595)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:645)
	... 1 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	... 8 more
Caused by: java.lang.InstantiationException: org.apache.fury.serializer.Serializer
	at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:501)
	at org.apache.fury.serializer.Serializers.createSerializer(Serializers.java:129)
	at org.apache.fury.serializer.Serializers.newSerializer(Serializers.java:104)
	at org.apache.fury.resolver.ClassResolver.registerSerializer(ClassResolver.java:624)
	at org.apache.fury.Fury.registerSerializer(Fury.java:190)
	at org.apache.fury.AbstractThreadSafeFury.lambda$registerSerializer$4(AbstractThreadSafeFury.java:52)
	at org.apache.fury.util.LoaderBinding.visitAllFury(LoaderBinding.java:61)
	at org.apache.fury.ThreadLocalFury.registerCallback(ThreadLocalFury.java:83)
	at org.apache.fury.AbstractThreadSafeFury.registerSerializer(AbstractThreadSafeFury.java:52)
	at io.quarkiverse.fury.FuryRecorder.registerClass(FuryRecorder.java:87)
	at io.quarkus.deployment.steps.FuryProcessor$registerClasses1265419993.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.FuryProcessor$registerClasses1265419993.deploy(Unknown Source)
	... 9 more

```

@chaokunyang can you take a look?

**Comment by chaokunyang** [comment]
@zhfeng which jdk version are you using?

**Comment by zhfeng** [comment]
```
openjdk version "21.0.5" 2024-10-15
OpenJDK Runtime Environment (Red_Hat-21.0.5.0.11-1) (build 21.0.5+11)
OpenJDK 64-Bit Server VM (Red_Hat-21.0.5.0.11-1) (build 21.0.5+11, mixed mode, sharing)
```

I think the issue is that the default value of serializer is `org.apache.fury.serializer.Serializer` and it should not be registered?

**Comment by chaokunyang** [comment]
Yes, it's an abstract class, and should  neverbe registered
